heat_template_version: 2014-10-16
description: 'SSH Known Hosts Config'

parameters:
  known_hosts:
    type: string

resources:

  SSHKnownHostsConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
<<<<<<< HEAD
      inputs:
        - name: known_hosts
          default: {get_param: known_hosts}
      config: |
        #!/bin/bash
        set -eux
        set -o pipefail

        echo "Creating ssh known hosts file"

        if [ ! -z "${known_hosts}" ]; then
          echo "${known_hosts}"
          echo -ne "${known_hosts}" > /etc/ssh/ssh_known_hosts
          chmod 0644 /etc/ssh/ssh_known_hosts
        else
          rm -f /etc/ssh/ssh_known_hosts
          echo "No ssh known hosts"
        fi
=======
      config:
        str_replace:
          params:
            KNOWN_HOSTS: {get_param: known_hosts}
          template: |
            #!/bin/bash
            set -eux
            set -o pipefail

            echo "Creating ssh known hosts file"

            if [ -d /etc/ssh/ssh_known_hosts ]; then
                rm -rf /etc/ssh/ssh_known_hosts
            fi
            cat <<EOF | grep -v '^$' >/etc/ssh/ssh_known_hosts
            KNOWN_HOSTS
            EOF
            if [ ! -s /etc/ssh/ssh_known_hosts ]; then
              echo "No known hosts"
              rm -f /etc/ssh/ssh_known_hosts
            else
              echo "$(cat /etc/ssh/ssh_known_hosts | wc -l) known hosts"
              chmod 0644 /etc/ssh/ssh_known_hosts
            fi
>>>>>>> 2c04151dedaa435a2a927377b4e5fa042b8fb6c0

outputs:
  OS::stack_id:
    description: The SSHKnownHostsConfig resource.
    value: {get_resource: SSHKnownHostsConfig}
